CREATE PROCEDURE sp_SoftDeleteCompany
	@CompanyPK UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRANSACTION

		UPDATE Companies
		SET IsDeleted = 1
		WHERE CompanyPK = @CompanyPK

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
				ROLLBACK TRANSACTION;
			THROW;
	END CATCH
END