CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Description NVARCHAR(MAX) NOT NULL,
    NotificationDate DATETIME NOT NULL DEFAULT GETDATE(),
    UserPK UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (UserPK) REFERENCES Users(UserPK)
);