services:
  - type: static
    name: kaizen-client
    buildCommand: yarn build
    staticPublishPath: dist
    rootDir: Kaizen/kaizen.client
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
