services:
  - type: web
    name: kaizen-client
    env: node
    buildCommand: yarn build
    startCommand: yarn start
    rootDir: Kaizen/kaizen.client
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
